baseURL = 'https://asungy.github.io/'
languageCode = 'en-us'
title = 'Alek Sung'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
user = "asungy"
hostname = "github.io"
published = true
readingTime = false
footerHtml = '© 2024 Alek Sung'

[params.author]
name = "Alek Sung"

[params.styles]
color = "#b073ff"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/asungy"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
